# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
