# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0003_alert_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 10, 12, 44, 618354, tzinfo=utc)),
        ),
    ]
