# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:46
from __future__ import unicode_literals

import alertbot.utils.util
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0005_auto_20160416_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 21, 56, 11, 960891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=alertbot.utils.util.getotp, max_length=10),
        ),
    ]
