# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:47
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0006_auto_20160416_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 21, 57, 54, 791757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
    ]
