# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 06:59
from __future__ import unicode_literals

import alertbot.utils.file_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0007_auto_20160416_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='', upload_to='images', validators=[alertbot.utils.file_validator.FileValidator(content_types=('image/png', 'image/jpeg', 'image/jpg'), max_size=3072000)]),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
