# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0009_auto_20160424_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='exp_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alert',
            name='exp_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
