# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertbot', '0010_auto_20160424_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='act_price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
